-- =============================================================================
-- TZ Fix — convert real-instant columns from `timestamp` to `timestamptz`
-- =============================================================================
--
-- Why this exists
-- ---------------
-- All `*_at` columns store real instants (when something happened), but they
-- were typed as `timestamp without time zone`. With the `postgres-js` session
-- TZ pin to America/Lima, they round-trip correctly *as long as that pin
-- holds*. Any tool that connects without the pin (raw `psql`, an external
-- ETL, a future runtime) reads them as if they were UTC, drifting by 5 hours.
--
-- `timestamptz` stores instants as UTC microseconds and is immune to that
-- drift. After this migration, the postgres-js session pin becomes redundant
-- defense-in-depth, not load-bearing. See docs/dev/datetime.md for the model.
--
-- Backfill semantics
-- ------------------
-- Existing rows were written under the Lima session pin → values are stored
-- as Lima wall-clock without zone (e.g. `2026-04-30 09:30:00`). The cast
-- `value AT TIME ZONE 'America/Lima'` interprets those naive values as Lima
-- local time, producing the correct UTC instant in the new `timestamptz` column.
--
-- Scope
-- -----
-- Application tables only (`packages/db/src/schema.ts`). Better Auth tables
-- (`user`, `session`, `account`, `verification`) are NOT touched here —
-- `auth-schema.ts` is regenerated by `pnpm auth:generate`, which would revert
-- a `withTimezone: true` change on the next regen and trigger db:push to
-- migrate them back. Address those separately if/when the auth schema is
-- pinned or owned.
--
-- IMPORTANT: run this migration AFTER deploying the application code that
-- declares `withTimezone: true` on each column. If run earlier, `db:push`
-- diff would suggest reverting these. The schema.ts change in this commit
-- aligns with the SQL below.
--
-- ROLLBACK: see the bottom of this file.
-- =============================================================================

BEGIN;

-- organizations
ALTER TABLE organizations
  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN updated_at TYPE timestamptz USING updated_at AT TIME ZONE 'America/Lima';

-- organization_members
ALTER TABLE organization_members
  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN updated_at TYPE timestamptz USING updated_at AT TIME ZONE 'America/Lima';

-- organization_invites
ALTER TABLE organization_invites
  ALTER COLUMN expires_at  TYPE timestamptz USING expires_at  AT TIME ZONE 'America/Lima',
  ALTER COLUMN accepted_at TYPE timestamptz USING accepted_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN created_at  TYPE timestamptz USING created_at  AT TIME ZONE 'America/Lima';

-- post (sample table from template; harmless to keep consistent)
ALTER TABLE post
  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'America/Lima';

-- facilities
ALTER TABLE facilities
  ALTER COLUMN onboarding_completed_at TYPE timestamptz USING onboarding_completed_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN created_at              TYPE timestamptz USING created_at              AT TIME ZONE 'America/Lima',
  ALTER COLUMN updated_at              TYPE timestamptz USING updated_at              AT TIME ZONE 'America/Lima';

-- courts
ALTER TABLE courts
  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN updated_at TYPE timestamptz USING updated_at AT TIME ZONE 'America/Lima';

-- peak_periods
ALTER TABLE peak_periods
  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN updated_at TYPE timestamptz USING updated_at AT TIME ZONE 'America/Lima';

-- blocked_slots
ALTER TABLE blocked_slots
  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'America/Lima';

-- bookings
ALTER TABLE bookings
  ALTER COLUMN cancelled_at TYPE timestamptz USING cancelled_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN confirmed_at TYPE timestamptz USING confirmed_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN created_at   TYPE timestamptz USING created_at   AT TIME ZONE 'America/Lima',
  ALTER COLUMN updated_at   TYPE timestamptz USING updated_at   AT TIME ZONE 'America/Lima';

-- booking_players
ALTER TABLE booking_players
  ALTER COLUMN joined_at TYPE timestamptz USING joined_at AT TIME ZONE 'America/Lima';

-- booking_activity
ALTER TABLE booking_activity
  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'America/Lima';

-- access_requests
ALTER TABLE access_requests
  ALTER COLUMN reviewed_at TYPE timestamptz USING reviewed_at AT TIME ZONE 'America/Lima',
  ALTER COLUMN created_at  TYPE timestamptz USING created_at  AT TIME ZONE 'America/Lima';

-- platform_admins
ALTER TABLE platform_admins
  ALTER COLUMN created_at TYPE timestamptz USING created_at AT TIME ZONE 'America/Lima';

-- Sanity check: counts unchanged (the casts are non-destructive — every
-- row gets a value, none of these columns become NOT NULL surprises).
DO $$
DECLARE
  cnt int;
BEGIN
  SELECT count(*) INTO cnt FROM information_schema.columns
  WHERE table_schema = 'public'
    AND data_type = 'timestamp without time zone'
    AND table_name IN (
      'organizations','organization_members','organization_invites',
      'facilities','courts','peak_periods','blocked_slots','bookings',
      'booking_players','booking_activity','access_requests','platform_admins',
      'post'
    );
  IF cnt > 0 THEN
    RAISE EXCEPTION 'Migration incomplete: % timestamp-without-tz columns remain on application tables', cnt;
  END IF;
END $$;

COMMIT;

-- =============================================================================
-- ROLLBACK (run only if needed). Note this re-introduces the bug — values
-- would be cast back to Lima wall-clock so they round-trip under the session
-- pin, but lose TZ awareness in the column.
-- =============================================================================
-- BEGIN;
--   ALTER TABLE organizations
--     ALTER COLUMN created_at TYPE timestamp USING created_at AT TIME ZONE 'America/Lima',
--     ALTER COLUMN updated_at TYPE timestamp USING updated_at AT TIME ZONE 'America/Lima';
--   -- … repeat for every table above …
-- COMMIT;
